### ISSUE TITLE
Problem with terralib dataset rename 

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#875]
With this is madatory to have a `output` field in fillcell:fillcells.
Waiting for resolution in the terralib.

**Comment by avancinirodrigo** [comment]
This problem still continues in terralib release 5.1.

**Comment by pedro-andrade-inpe** [comment]
Waiting for Release 5.2. It seems that it was already fixed but it is in the develop branch.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, the problem still continues in release 5.1 and worse, there is no implementation to shape. So is not possible remove `output` argument #902 yet.

**Comment by avancinirodrigo** [comment]
This problem impacts in #1217 as well.
The problem can be verified in TerraLib:saveLayerAs() function.

**Comment by avancinirodrigo** [comment]
Review after #1377

**Comment by avancinirodrigo** [comment]
It was not implemented yet, source code in TerraLib system:
```cpp
void te::ogr::Transactor::renameDataSet(const std::string& /*name*/, const std::string& /*newName*/)
{
}
```

**Comment by avancinirodrigo** [comment]
It was resolved for Postgis in TerraLib 5.3, but it still doesn't work to files.
